= Project: {First_Task_IOT}

=== Author: azmm12.
=== Email: {Abdulazizmmutiri@gmail.com} .
=== Date: 22/07/2022 .
=== Revision: version#1 .
=== License: Public Domain .

== Description of project:
Designing Web Audio Speech Recognition using javascript.

== Installation Steps:
1. Download Virtual box .
2. Download Ubuntu LTS .
3. Type commands below to install ROS :

locale  

sudo apt update && sudo apt install locales

sudo locale-gen en_US en_US.UTF-8

sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

export LANG=en_US.UTF-8

apt-cache policy | grep universe

sudo apt install software-properties-common

sudo add-apt-repository universe

sudo apt update && sudo apt install curl gnupg lsb-release

sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update

sudo apt upgrade

sudo apt install ros-humble-desktop

source /opt/ros/humble/setup.bash

=== Folder structure

....
 ROS_Task_1
  └── ReadMe.adoc      => this file
....

=== Contributing
To contribute to this project please contact azmm12 https://id.arduino.cc/azmm12

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]

