= Project: {ROS-Installation-and-Example-Running}

=== Author: azmm12.
=== Email: {Abdulazizmmutiri@gmail.com} .
=== Date: 22/07/2022 .
=== Revision: version#1 .
=== License: Public Domain .

== Description of project:
Downloading Ubuntu and ROS with the help of virtual box.

== Task 1 : ROS HUMBLE Installation Steps: (im using Ubuntu 22.04)
1. Download Virtual box .
2. Download Ubuntu LTS .
3. Type commands below to install ROS :

locale  

sudo apt update && sudo apt install locales

sudo locale-gen en_US en_US.UTF-8

sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

export LANG=en_US.UTF-8

apt-cache policy | grep universe

sudo apt install software-properties-common

sudo add-apt-repository universe

sudo apt update && sudo apt install curl gnupg lsb-release

sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update

sudo apt upgrade

sudo apt install ros-humble-desktop

source /opt/ros/humble/setup.bash

Try some examples
If you installed ros-humble-desktop above you can try some examples.
In one terminal, source the setup file and then run a C++ talker:

source /opt/ros/humble/setup.bash
ros2 run demo_nodes_cpp talker

In another terminal source the setup file and then run a Python listener:

source /opt/ros/humble/setup.bash
ros2 run demo_nodes_py listener

For Task 2 : Installing ROS2 on jetson nano:
1.install VirtualBox .
2.Install XUbuntu .
3.Install balena .
5.Write XUbuntu to flash or card using balena .
4.Now preform same steps for Task1 Because its ROS2 .

=== Folder structure

....
 ROS_Task_1
  └── ReadMe.adoc      => this file
  └── pic1.png      => picture of running example 1
  └── pic2.png      => picture of running example 2
....
